---

- name: LABS setup
  hosts: labs
  become: true
  tasks:

  ############ SETUP ############

    - name: Install a list of packages
      ansible.builtin.apt:
        update_cache: yes
        pkg:
        - nginx
        - net-tools
        - stress-ng

    - name: Copy Site files
      ansible.builtin.copy:
        src: ./www/index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: '0644'
      tags: web